plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/opt/build/repo/website/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/opt/build/repo"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]