name: pull-request
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  code:
    uses: unional/.github/.github/workflows/pnpm-verify.yml@main
    secrets: inherit
    with:
      node-version: "[18]"
